---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/address-pool: ftps-ip
  labels:
    app: ftps-app
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: http
  - port: 30020
    name: ftps-data4
  - port: 30021
    name: ftps-data1
  - port: 30022
    name: ftps-data2
  - port: 30023
    name: ftps-data3
  selector:
    app: ftps-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
      - name: ftps
        image: ft_ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'ps aux | egrep [t]elegraf'
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /ftp/user
          name: ftps-volume
        ports:
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        - containerPort: 30022
        - containerPort: 30023
      volumes:
      - name: ftps-volume
        hostPath:
          path: /data
          type: DirectoryOrCreate

      
