---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: ft_grafana
        ports:
        - containerPort: 3000
          name: http
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'ps aux | egrep [t]elegraf'
          initialDelaySeconds: 10
          periodSeconds: 5
